// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXQrykz0PUcTauY7bhPgGeglds-2X8eQU',
    appId: '1:801482093726:web:597abe08fd3683533df78f',
    messagingSenderId: '801482093726',
    projectId: 'chat-app-project-8ee77',
    authDomain: 'chat-app-project-8ee77.firebaseapp.com',
    storageBucket: 'chat-app-project-8ee77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWw3jP-0yuhU34e6_IwSZM03PWC35MW_U',
    appId: '1:801482093726:android:9246b6a1aa8934153df78f',
    messagingSenderId: '801482093726',
    projectId: 'chat-app-project-8ee77',
    storageBucket: 'chat-app-project-8ee77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkcNYhbCE53veW4b5uA_cyVjquwI1GlNo',
    appId: '1:801482093726:ios:eb49bfb2735936b03df78f',
    messagingSenderId: '801482093726',
    projectId: 'chat-app-project-8ee77',
    storageBucket: 'chat-app-project-8ee77.appspot.com',
    iosBundleId: 'com.example.trialChat',
  );
}
